import = [
    # "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
    "~/.config/alacritty/gruvbox.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines = 80 }
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

[font]
normal.family = "Hack Nerd Font Mono"

size = 16
